### ISSUE TITLE
Where is Apple's new "Music app" xml file location?

### ISSUE THREAD

**Issue by wchorski** [jasmith79/playlistrs#3]
I've migrated everything from iTunes to Apple's new "Music" app

In my library I still have the `iTunes Library.xml` file, but the playlists are old and the file paths are the same.

i.e. - no new playlists created in the "Music" app do not show in `iTunes Library.xml`. Also, all the old file paths shown are related to my Windows install (like `C:/music`). I've moved everything to a MacBook, so I assume the paths would at least start with `/Volumes` So as I understand it, this is just a legacy file they keep around to import into the new app

So my question is, where is this new `.xml` file? I checked `~/Music/Music/Music Library/Library.musicdb` but that is a special file that can't be read in a text editor

Is your tool only for iTunes or is it for Apple Music too? If so, then how or where is the file I need to process to batch export playlists?

**Comment by jared-smith-kr** [comment]
It should work for both, although all of my playlists are purely for local files, I haven't tried this with any playlists for their streaming service. Sounds like yours are too. Open up Apple Music and in the context menu at the top of the screen do File -> Library -> Export Library to generate the XML file, then you should be able to run the CLI tool on it to generate m3u playlists for the ones you made in Apple Music. If you have old ones from your Windows install that you haven't migrated already you should also be able to run the CLI over the old windows one with the flag to replace the path with your current macbook path and generate m3u's for those for your macbook that you can then import in Apple Music by doing File -> Import in the context menu.

**Comment by jasmith79** [comment]
I've added instructions to the README for how to get the XML file.
