### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by itwasmattgregg** [jasmith79/playlistrs#4]
Could you add a how to guide and setup section to the README?

**Comment by jasmith79** [comment]
I've added usage instructions. I'm going to hold off for now on installation instructions, as I'm planning to publish to crates.io. Right now you need to compile it yourself, but I will update this thread when I get it published.

**Comment by jasmith79** [comment]
Closing with [#9](https://github.com/jasmith79/playlistrs/pull/9). You can now install via cargo or there's a precompiled binary for Apple Silicon.
